# Generated by Django 4.1 on 2024-06-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("keywords", models.CharField(max_length=200)),
                ("publish_time", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
